
services:
  udemynewmicroservice.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/udemyTenant 
      - IdentityOption:Issuer=http://keycloak:8080/realms/udemyTenant
      - ConnectionStrings:Redis=redis.db.basket:6379,password=Password12 
    ports:
      - "8080"
    depends_on:
      - redis.db.basket
      - rabbitmq
    restart: always


  udemynewmicroservice.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/udemyTenant 
      - IdentityOption:Issuer=http://keycloak:8080/realms/udemyTenant
      - MongoOption:ConnectionString=mongodb://myuser:Password12@mongo.db.catalog:27017 
    ports:
      - "8080"
    depends_on:
      - mongo.db.catalog
      - rabbitmq
    restart: always


  udemynewmicroservice.discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/udemyTenant 
      - IdentityOption:Issuer=http://keycloak:8080/realms/udemyTenant
      - MongoOption:ConnectionString=mongodb://myuser:Password12@mongo.db.discount:27017 
    ports:
      - "8080"
    depends_on:
      - mongo.db.discount
      - rabbitmq
    restart: always


  udemynewmicroservice.file.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/udemyTenant 
      - IdentityOption:Issuer=http://keycloak:8080/realms/udemyTenant
    ports:
      - "8080"
    restart: always
    depends_on:
      - rabbitmq



  udemynewmicroservice.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - IdentityOption:Address=http://keycloak:8080/realms/udemyTenant 
      - IdentityOption:Issuer=http://keycloak:8080/realms/udemyTenant
    ports:
      - "8080"
    restart: always



  udemynewmicroservice.order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/udemyTenant 
      - IdentityOption:Issuer=http://keycloak:8080/realms/udemyTenant
      - AddressUrlOption:PaymentUrl=http://udemynewmicroservice.payment.api:8080
      - ConnectionStrings:SqlServer=Server=sqlserver.db.order,1433;Database=OrderDockerDb;User=Sa;Password=Password12*;Trusted_Connection=False;TrustServerCertificate=True;Integrated Security=False
    ports:
      - "8080"
    depends_on:
      - sqlserver.db.order
      - rabbitmq
    restart: always
  udemynewmicroservice.payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BusOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/udemyTenant 
      - IdentityOption:Issuer=http://keycloak:8080/realms/udemyTenant
    ports:
      - "8080"
    restart: always
    depends_on:
      - rabbitmq


  udemynewmicroservice.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - MicroserviceOption:Catalog:BaseAddress=http://udemynewmicroservice.catalog.api:8080
      - MicroserviceOption:File:BaseAddress=http://udemynewmicroservice.file.api:8080
      - MicroserviceOption:Basket:BaseAddress=http://udemynewmicroservice.basket.api:8080
      - MicroserviceOption:Discount:BaseAddress=http://udemynewmicroservice.discount.api:8080
      - MicroserviceOption:Order:BaseAddress=http://udemynewmicroservice.order.api:8080
      - GatewayOption:BaseAddress=http://udemynewmicroservice.gateway:8080
      - IdentityOption:Address=http://keycloak:8080/realms/udemyTenant
      - IdentityOption:BaseAddress=http://keycloak:8080
    ports:
      - "5050:8080"
    restart: always

